# Generated by Django 5.2.4 on 2025-07-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choices",
            new_name="Choice",
        ),
    ]
